name: Code Quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Ruff
        uses: chartboost/ruff-action@v1

