name: Code Quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Ruff
        uses: chartboost/ruff-action@v1
      
      - name: Run ruff
        run: |
          ruff check $(git ls-files '*.py' '*.ipynb')

