name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      
      - name: Install dependencies
      - run: |
        python -m pip install --upgrade pip
        pip install black pylint
      
      - name: Formating code with black
      - run: black --diff --check $(git ls-files '*.py')
      
      - name: Analyzing code with pylint & mypy
      - run: pylint -d C0114 $(git ls-files '*.py')

